importScripts("license_config.js");

const LICENSE_DEFAULTS={
  deviceId:null,licenseId:null,activationToken:null,licenseExpiresAt:null,licenseLabel:null,
  licenseValid:false,lastLicenseCheck:0,lastLicenseValidAt:0,updateAvailable:false,
  updateRequired:false,latestVersion:null,minimumVersion:null,updateMessage:null,
  updateUrl:null,licenseMaxMajorVersion:4
};
const UPDATE_FEED="https://raw.githubusercontent.com/user1242151321/vtowatcher/main/updates/latest.json";
const serverUrl=()=>String(LICENSE_CONFIG.SERVER_URL||"").replace(/\/+$/,"");
const serverConfigured=()=>/^https:\/\//i.test(serverUrl())&&!serverUrl().includes("YOUR-WORKER-URL");
const extensionVersion=()=>chrome.runtime.getManifest().version;
const parse=v=>String(v||"0.0.0").replace(/^v/i,"").split(".").slice(0,3).map(x=>Number(String(x).match(/^\d+/)?.[0]||0));
function compare(a,b){const A=parse(a),B=parse(b);while(A.length<3)A.push(0);while(B.length<3)B.push(0);for(let i=0;i<3;i++){if(A[i]>B[i])return 1;if(A[i]<B[i])return-1;}return 0;}
async function updateInfo(result={}){try{const r=await fetch(UPDATE_FEED,{cache:"no-store"});if(!r.ok)return result;const x=await r.json();const latest=String(x.latestVersion||"").trim(),minimum=String(x.minimumVersion||"0.0.0").trim(),current=extensionVersion();if(!latest)return result;return {...result,updateAvailable:compare(current,latest)<0,updateRequired:compare(current,minimum)<0,latestVersion:latest,minimumVersion:minimum,updateMessage:String(x.message||"").trim()||null,updateUrl:String(x.downloadUrl||"").trim()||null,updateSha256:String(x.sha256||"").trim()||null};}catch{return result;}}
async function indicator(result={}){const required=Boolean(result.updateRequired)||result.reason==="update_required",available=required||Boolean(result.updateAvailable);if(!available){await chrome.action.setBadgeText({text:""});return;}await chrome.action.setBadgeText({text:required?"!":"UP"});await chrome.action.setBadgeBackgroundColor({color:required?"#ef4444":"#f59e0b"});const latest=result.latestVersion||"new",stored=await chrome.storage.local.get({lastUpdateNoticeVersion:null,notificationsEnabled:true});if(result.updateAvailable&&stored.lastUpdateNoticeVersion!==latest){await chrome.storage.local.set({lastUpdateNoticeVersion:latest});if(stored.notificationsEnabled)chrome.notifications.create({type:"basic",iconUrl:"icons/icon128.png",title:required?"VTO Watcher update required":"VTO Watcher update available",message:result.updateMessage||`Version ${latest} is available.`});}}
async function deviceId(){const d=await chrome.storage.local.get({deviceId:null});if(d.deviceId)return d.deviceId;const id=crypto.randomUUID();await chrome.storage.local.set({deviceId:id});return id;}
async function post(path,body){const r=await fetch(`${serverUrl()}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});let data={};try{data=await r.json();}catch{}if(!r.ok){const e=new Error(data.message||data.error||`HTTP ${r.status}`);e.code=data.code||"server_error";e.status=r.status;e.details=data;throw e;}return data;}
async function persistVersion(x={}){await chrome.storage.local.set({updateAvailable:Boolean(x.updateAvailable),updateRequired:Boolean(x.updateRequired),latestVersion:x.latestVersion||null,minimumVersion:x.minimumVersion||null,updateMessage:x.updateMessage||null,updateUrl:x.updateUrl||null,updateSha256:x.updateSha256||null,licenseMaxMajorVersion:Number.isFinite(Number(x.maxMajorVersion))?Number(x.maxMajorVersion):4});}
async function clearLicense(){await chrome.storage.local.set({licenseId:null,activationToken:null,licenseExpiresAt:null,licenseLabel:null,licenseValid:false,lastLicenseCheck:0,lastLicenseValidAt:0,updateAvailable:false,updateRequired:false,latestVersion:null,minimumVersion:null,updateMessage:null,updateUrl:null,updateSha256:null,licenseMaxMajorVersion:4});}
async function activateLicense(key){if(!serverConfigured())return{ok:false,valid:false,reason:"setup_required",message:"License server URL has not been configured yet."};const clean=String(key||"").trim().toUpperCase();if(!clean)return{ok:false,valid:false,reason:"missing_key",message:"Enter a license key."};const id=await deviceId();try{const server=await post("/activate",{key:clean,deviceId:id,extensionVersion:extensionVersion()}),result=await updateInfo(server),now=Date.now();await chrome.storage.local.set({licenseId:result.licenseId,activationToken:result.activationToken,licenseExpiresAt:result.expiresAt||null,licenseLabel:result.label||null,licenseValid:true,lastLicenseCheck:now,lastLicenseValidAt:now});await persistVersion(result);await indicator(result);return{ok:true,valid:true,deviceId:id,...result};}catch(e){const d=e.details||{};await persistVersion(d);await indicator({...d,reason:e.code});return{ok:false,valid:false,reason:e.code||"activation_failed",message:e.message||"Activation failed.",...d};}}
async function validateRemote(stored){const id=await deviceId();try{const server=await post("/validate",{licenseId:stored.licenseId,activationToken:stored.activationToken,deviceId:id,extensionVersion:extensionVersion()}),result=await updateInfo(server),now=Date.now();await chrome.storage.local.set({licenseValid:true,licenseExpiresAt:result.expiresAt||stored.licenseExpiresAt||null,licenseLabel:result.label||stored.licenseLabel||null,lastLicenseCheck:now,lastLicenseValidAt:now});await persistVersion(result);await indicator(result);return{ok:true,valid:true,deviceId:id,offlineGrace:false,...result};}catch(e){const d=e.details||{};await persistVersion(d);if(e.status>=400&&e.status<500){await chrome.storage.local.set({licenseValid:false,lastLicenseCheck:Date.now()});return{ok:false,valid:false,deviceId:id,reason:e.code||"license_rejected",message:e.message||"License rejected by server.",...d};}const now=Date.now(),within=stored.lastLicenseValidAt&&(now-Number(stored.lastLicenseValidAt))<=LICENSE_CONFIG.OFFLINE_GRACE_MS;if(stored.licenseValid&&within)return{ok:true,valid:true,offlineGrace:true,expiresAt:stored.licenseExpiresAt||null,label:stored.licenseLabel||null,deviceId:id,message:"Using temporary offline license grace period."};await chrome.storage.local.set({licenseValid:false,lastLicenseCheck:now});return{ok:false,valid:false,reason:"server_unreachable",message:"Could not reach the license server.",deviceId:id};}}
async function licenseStatus(force=false){const id=await deviceId();if(!serverConfigured())return{ok:false,valid:false,reason:"setup_required",message:"Set LICENSE_CONFIG.SERVER_URL in license_config.js.",deviceId:id};const s=await chrome.storage.local.get(LICENSE_DEFAULTS);if(!s.licenseId||!s.activationToken)return{ok:true,valid:false,reason:"not_activated",message:"This device has not been activated.",deviceId:id};if(s.licenseExpiresAt){const expiry=new Date(s.licenseExpiresAt).getTime();if(Number.isFinite(expiry)&&Date.now()>expiry){await chrome.storage.local.set({licenseValid:false});return{ok:true,valid:false,reason:"expired",message:"This license has expired.",expiresAt:s.licenseExpiresAt,deviceId:id};}}
  const fresh=s.licenseValid&&s.lastLicenseCheck&&(Date.now()-Number(s.lastLicenseCheck))<LICENSE_CONFIG.VALIDATE_EVERY_MS;
  if(!force&&fresh){const result={ok:true,valid:true,expiresAt:s.licenseExpiresAt||null,label:s.licenseLabel||null,deviceId:id,offlineGrace:false,updateAvailable:Boolean(s.updateAvailable),updateRequired:Boolean(s.updateRequired),latestVersion:s.latestVersion||null,minimumVersion:s.minimumVersion||null,updateMessage:s.updateMessage||null,updateUrl:s.updateUrl||null,maxMajorVersion:s.licenseMaxMajorVersion||4};await indicator(result);return result;}
  return validateRemote(s);
}
async function deactivate(){const s=await chrome.storage.local.get(LICENSE_DEFAULTS),id=await deviceId();if(serverConfigured()&&s.licenseId&&s.activationToken){try{await post("/deactivate",{licenseId:s.licenseId,activationToken:s.activationToken,deviceId:id});}catch{}}await clearLicense();return{ok:true,valid:false};}

chrome.runtime.onInstalled.addListener(async()=>{await deviceId();const defaults={armed:false,paused:false,refreshSeconds:5,autoConfirm:false,testMode:false,soundEnabled:true,notificationsEnabled:true,tabFlashEnabled:true,minHours:0,startAfter:"any",preferLongest:true,maxAcceptsPerArm:1,acceptedThisArm:0,armedStartedAt:0};const current=await chrome.storage.local.get(defaults);await chrome.storage.local.set({...defaults,...current});});
chrome.runtime.onMessage.addListener((m,sender,send)=>{if(!m||typeof m!=="object")return;if(m.type==="activateLicense"){activateLicense(m.key).then(send);return true;}if(m.type==="licenseStatus"){licenseStatus(Boolean(m.force)).then(send);return true;}if(m.type==="deactivateLicense"){deactivate().then(send);return true;}if(m.type==="notify"){(async()=>{const lic=await licenseStatus(false);if(!lic.valid){send({ok:false,reason:"license_invalid"});return;}const st=await chrome.storage.local.get({notificationsEnabled:true});if(!st.notificationsEnabled){send({ok:false,reason:"notifications_disabled"});return;}chrome.notifications.create({type:"basic",iconUrl:"icons/icon128.png",title:m.title||"VTO Watcher",message:m.message||""},()=>send({ok:!chrome.runtime.lastError}));})();return true;}if(m.type==="getState"){chrome.storage.local.get(null).then(send);return true;}if(m.type==="setState"){chrome.storage.local.set(m.patch||{}).then(()=>send({ok:true}));return true;}});
